name: Schedule Test

on:
  schedule:
    - cron: '0 01 * * *'
    - cron: '0 02 * * *'
    - cron: '0 03 * * *'
    - cron: '0 04 * * *'
    - cron: '0 05 * * *'
    - cron: '0 06 * * *'
    - cron: '0 07 * * *'
    - cron: '0 08 * * *'
    - cron: '0 09 * * *'
    - cron: '0 10 * * *'
    - cron: '0 11 * * *'
    - cron: '0 12 * * *'
    - cron: '0 13 * * *'
    - cron: '0 14 * * *'
    - cron: '0 15 * * *'
    - cron: '0 16 * * *'
    - cron: '0 17 * * *'
    - cron: '0 18 * * *'
    - cron: '0 19 * * *'
    - cron: '0 20 * * *'
    - cron: '0 21 * * *'
    - cron: '0 22 * * *'
    - cron: '0 23 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Time
        run: |
          echo "Current Time (UTC): $(date)"
          echo "Expected KST Time: $(date -d '+9 hours')"
